-- Recreate the redundant quote index dropped by the up migration, so the schema
-- round-trips. It is a strict left prefix of uq_quotes_asset_day_source and
-- serves no plan that index cannot, but reversing the migration should restore
-- the schema exactly as it was.
CREATE INDEX IF NOT EXISTS idx_quotes_asset_day ON quotes(asset_id, day);

-- The VACUUM itself is not reversed: it only rewrites the file to reclaim free
-- pages, changing no schema and no data.

-- Derived valuation rows deleted by the up migration are not restored. They
-- are regenerated by the normal startup portfolio-history backfill.
