//! Expected numbers are transcribed from external sources, never regenerated by the engine.
use super::*;
use serde_json::json;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct SimulatorCase {
    id: String,
    principal: f64,
    annual_rate: f64,
    amortization_years: usize,
    frequency: LoanFrequency,
    extra_at_first_payment: f64,
    payment: f64,
    term_payments: usize,
    term_principal: f64,
    term_interest: f64,
    schedule: Vec<ReferenceRow>,
}

#[derive(Deserialize)]
struct ReferenceRow {
    period: usize,
    interest: f64,
    balance: f64,
}

fn near(actual: f64, expected: f64, tolerance: f64, label: &str) {
    assert!(
        (actual - expected).abs() <= tolerance,
        "{label}: actual {actual}, reference {expected}, tolerance {tolerance}"
    );
}

#[test]
fn fcac_monthly_and_accelerated_reference_schedules() {
    let fixtures: Value = serde_json::from_str(include_str!("fixtures.json")).unwrap();
    let fixture = &fixtures["fcac"];
    let cases: Vec<SimulatorCase> = serde_json::from_value(fixture["cases"].clone()).unwrap();
    for case in cases {
        // FCAC's ordinary biweekly example prorates the monthly rate instead of using
        // the effective 26-period rate. Preserve it as evidence, not as this contract.
        if case.frequency == LoanFrequency::Biweekly {
            continue;
        }
        let count = case.amortization_years * case.frequency.periods() as usize;
        let payment = payment_amount(
            case.principal,
            case.annual_rate,
            count,
            case.frequency,
            InterestMethod::Semiannual,
        )
        .unwrap();
        near(money(payment), case.payment, 0.001, &case.id);
        let start: NaiveDate = "2020-01-01".parse().unwrap();
        let first: NaiveDate = if case.frequency == LoanFrequency::Monthly {
            "2020-02-01"
        } else {
            "2020-01-15"
        }
        .parse()
        .unwrap();
        let as_of = payment_date(first, case.term_payments - 1, case.frequency).unwrap();
        let mut metadata = json!({
            "loan_projection": {
                "version": 1, "annualRate": case.annual_rate, "paymentAmount": payment,
                "frequency": case.frequency, "interestMethod": "semiannual",
                "firstPaymentDate": first, "paymentCount": count
            }
        });
        if case.extra_at_first_payment > 0.0 {
            metadata[LOAN_EVENTS_KEY] = json!([{
                "type": "extra_repayment", "effectiveDate": first,
                "amount": case.extra_at_first_payment
            }]);
        }
        let result = calculate_loan(&LoanCalculationRequest {
            metadata,
            as_of,
            balances: vec![LoanBalance {
                date: start,
                balance: case.principal,
                notes: None,
            }],
            payments: Vec::new(),
        })
        .unwrap();
        // Two independent quantizations per period (interest and payment), each
        // bounded by half a cent. Propagate their worst-case balance error through
        // the annuity. This is a derived bound, not an empirically widened tolerance.
        let rate = InterestMethod::Semiannual.periodic_rate(case.annual_rate, case.frequency);
        let rounding_bound = |n: usize| 0.01 * ((1.0 + rate).powi(n as i32) - 1.0) / rate + 0.02;
        near(
            result.current_balance,
            case.principal - case.term_principal,
            rounding_bound(case.term_payments),
            &case.id,
        );
        near(
            result.interest_to_date,
            case.term_interest,
            rounding_bound(case.term_payments) + 0.005 * case.term_payments as f64,
            &case.id,
        );
        for expected in case.schedule {
            // FCAC's partial-final-payment interest has a documented inconsistency
            // in both accelerated and prepayment scenarios. Check conservation
            // separately below; do not treat that number as a golden assertion.
            if expected.period > case.term_payments
                && (case.extra_at_first_payment > 0.0
                    || case.frequency == LoanFrequency::AcceleratedBiweekly)
            {
                continue;
            }
            let row = &result.rows[expected.period];
            near(
                row.interest,
                expected.interest,
                0.01 + rate * rounding_bound(expected.period - 1),
                &case.id,
            );
            near(
                row.balance,
                expected.balance,
                rounding_bound(expected.period),
                &case.id,
            );
        }
        for row in &result.rows {
            near(
                row.payment,
                row.principal + row.interest,
                1e-8,
                "payment conservation",
            );
            near(
                row.balance,
                row.opening_balance - row.principal + row.balance_adjustment,
                1e-8,
                "balance conservation",
            );
        }
        if result.residual_balance == 0.0 {
            let final_row = result.rows.last().unwrap();
            near(
                final_row.payment,
                final_row.opening_balance + final_row.interest,
                1e-8,
                "final payment cap",
            );
        }
    }
}

#[test]
fn cfpb_statement_principal_and_interest_exclude_escrow_and_fees() {
    let fixtures: Value = serde_json::from_str(include_str!("fixtures.json")).unwrap();
    let source = &fixtures["cfpb"];
    let n = |key: &str| source[key].as_f64().unwrap();
    let payment = n("regularPayment") - n("escrowDue");
    let result = calculate_loan(&LoanCalculationRequest {
        metadata: json!({"loan_projection": {
            "version": 1, "annualRate": n("annualRate"), "paymentAmount": payment,
            "frequency": "monthly", "interestMethod": "nominal_periodic",
            "firstPaymentDate": "2012-04-01", "paymentCount": 1
        }}),
        // Synthetic period start: the specimen supplies no complete origination history.
        balances: vec![LoanBalance {
            date: "2012-03-01".parse().unwrap(),
            balance: n("outstandingPrincipal"),
            notes: None,
        }],
        as_of: "2012-04-01".parse().unwrap(),
        payments: Vec::new(),
    })
    .unwrap();
    near(
        result.rows[1].interest,
        n("interestDue"),
        0.001,
        "CFPB interest",
    );
    near(
        result.rows[1].principal,
        n("principalDue"),
        0.001,
        "CFPB principal",
    );
    near(
        result.current_balance,
        n("outstandingPrincipal") - n("principalDue"),
        0.001,
        "CFPB closing balance",
    );
}

#[test]
fn nationwide_statement_confirmation_reconciles_unmodelled_charges() {
    let fixtures: Value = serde_json::from_str(include_str!("fixtures.json")).unwrap();
    let source = &fixtures["nationwide"];
    let n = |key: &str| source[key].as_f64().unwrap();
    let unmodelled = n("interestCharged") + n("termChangeFee") + n("insurancePremium");
    near(
        n("openingBalance") - n("payments") * n("monthlyPayment") + unmodelled,
        n("closingBalance"),
        1e-8,
        "Nationwide published account reconciliation",
    );
    // Deliberately incomplete projection. This tests reconciliation, not the
    // lender's unspecified interest convention or its fee/insurance servicing.
    let result = calculate_loan(&LoanCalculationRequest {
        metadata: json!({"loan_projection": {
            "version": 1, "annualRate":0, "paymentAmount":n("monthlyPayment"),
            "frequency":"monthly", "firstPaymentDate":"2025-01-01",
            "amortizationEndDate":"2025-12-31"
        }}),
        balances: vec![
            LoanBalance {
                date: "2024-12-31".parse().unwrap(),
                balance: n("openingBalance"),
                notes: None,
            },
            LoanBalance {
                date: "2025-12-31".parse().unwrap(),
                balance: n("closingBalance"),
                notes: None,
            },
        ],
        as_of: "2025-12-31".parse().unwrap(),
        payments: Vec::new(),
    })
    .unwrap();
    assert_eq!(result.current_balance, n("closingBalance"));
    let last = result.rows.last().unwrap();
    near(
        last.balance_adjustment,
        unmodelled,
        1e-8,
        "Unmodelled statement charges",
    );
    assert_eq!(last.payment, 0.0);
    assert_eq!(last.principal, 0.0);
}
